### ISSUE TITLE
Working with room aliases

### ISSUE THREAD

**Issue by AlexDaniel** [matiaslina/perl6-matrix-client#14]
This ticket is similar to https://github.com/matiaslina/perl6-matrix-client/issues/8

Basically there are no methods for working with aliases. For example, getting a local address of a room is not possible.

**Comment by matiaslina** [comment]
Added in https://github.com/matiaslina/perl6-matrix-client/commit/89c178e90786f668c15506f7e52206214ac29ed6 the three endpoints to work with aliases (get, add and delete aliases).
