### ISSUE TITLE
module install appears to be broken - Could not find JSON::Tiny

### ISSUE THREAD

**Issue by melezhik** [matiaslina/perl6-matrix-client#17]
Hi!

http://repo.westus.cloudapp.azure.com/sparky/report/debian/433

HTH

Best

Alexey

**Comment by matiaslina** [comment]
Hi @melezhik . Thanks for the report!

I fixed that issue in  https://github.com/matiaslina/perl6-matrix-client/commit/e39257df2688137d57d88d502f7198425d5dfcd5 but never raised the module version :/

**Comment by melezhik** [comment]
You are welcome. You can use
http://repo.westus.cloudapp.azure.com/rakudist2/ to test it.

On May 7, 2020 5:57 PM, "Matias Linares" <notifications@github.com> wrote:

Hi @melezhik <https://github.com/melezhik> . Thanks for the report!

I fixed that issue in e39257d
<https://github.com/matiaslina/perl6-matrix-client/commit/e39257df2688137d57d88d502f7198425d5dfcd5>
but never raised the module version :/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matiaslina/perl6-matrix-client/issues/17#issuecomment-625538069>,
or unsubscribe

**Comment by melezhik** [comment]
looks good now. http://repo.westus.cloudapp.azure.com/sparky/report/debian/453

**Comment by matiaslina** [comment]
Cool! Seems like the installation from CPAN also [works](http://repo.westus.cloudapp.azure.com/sparky/report/debian/483) :)

Thanks again for the report
