### ISSUE TITLE
[regression] Not possible to login anymore

### ISSUE THREAD

**Issue by AlexDaniel** [matiaslina/perl6-matrix-client#6]
The problem was introduced in e03a435e48bdc59cd32aad8f47b31630b446945e. Basically, method login has a return constraint (`Bool`), but the sub has this as the last line:

```
    $!device-id = $data<device_id>; 
```

So it ends up returning a Str (which fails).

**Comment by matiaslina** [comment]
I've changed the signature to `multi method login(Str $username, Str $password)` (without the `returns Bool`). It was not necessary since now with an error the client throws `X::Matrix::Response` with the type and description of the error.
